

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: signupdb
      POSTGRES_USER: signupuser
      POSTGRES_PASSWORD: signuppass
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
